@extends('layouts.app')
@section('title',$convidado->exists?'Editar convidado':'Novo convidado')
@push('styles')<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" rel="stylesheet"><style>.curriculo-field,.descricao-field{position:relative;clear:both}.curriculo-editor-wrapper{overflow:hidden;border-radius:.5rem;background:#fff}.curriculo-editor-wrapper .ql-toolbar{border-radius:.5rem .5rem 0 0}.curriculo-editor-wrapper .ql-container{height:260px;overflow:hidden;border-radius:0 0 .5rem .5rem}.curriculo-editor-wrapper .ql-editor{height:100%;overflow-y:auto}.descricao-field{margin-top:1.5rem}.social-row{background:#f8fafc;border:1px solid #e9ecef;border-radius:.6rem;padding:.75rem}.foto-upload-panel{background:#f8fafc;border:1px solid #e3e9ef;border-radius:.75rem;padding:1rem}.foto-preview{width:150px;height:150px;object-fit:cover;border-radius:50%;border:3px solid #fff;box-shadow:0 4px 16px rgba(16,42,67,.14)}.foto-colar-area{background:#fff;border:2px dashed #adb5bd;cursor:pointer;min-height:96px;transition:border-color .15s,background-color .15s}.foto-colar-area:focus,.foto-colar-area.arrastando{background:#eef5ff;border-color:#0d6efd;box-shadow:0 0 0 .25rem rgba(13,110,253,.12);outline:0}.foto-colar-area .bi{font-size:2rem}.crop-canvas{max-width:100%;background:#212529;cursor:move;touch-action:none}</style>@endpush
@section('content')
<div class="mb-4"><h1 class="page-title">{{$convidado->exists?'Editar convidado':'Novo convidado'}}</h1><p class="page-description mb-0">Preencha os dados do professor convidado.</p></div>
<form id="convidadoForm" method="POST" enctype="multipart/form-data" action="{{$convidado->exists?route('convidados.update',$convidado):route('convidados.store')}}">@csrf @if($convidado->exists)@method('PUT')@endif
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">Dados do convidado</h2></div><div class="card-body p-4">@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif<div class="row g-3">
<div class="col-12 col-md-2"><label class="form-label" for="titulacao">Titulação</label><input type="text" class="form-control" id="titulacao" name="titulacao" maxlength="255" value="{{ old('titulacao', $convidado->titulacao) }}"></div>
<div class="col-12 col-md-4"><label class="form-label" for="nome">Nome *</label><input class="form-control" id="nome" name="nome" maxlength="255" required value="{{ old('nome', $convidado->nome) }}"></div>
<div class="col-12 col-md-6"><label class="form-label" for="sobrenome">Sobrenome</label><input class="form-control" id="sobrenome" name="sobrenome" maxlength="255" value="{{ old('sobrenome', $convidado->sobrenome) }}"></div>
<div class="col-12 col-md-6"><label class="form-label" for="email">E-mail</label><input type="email" class="form-control" id="email" name="email" maxlength="150" value="{{ old('email', $convidado->email) }}"></div>
<div class="col-12 col-md-3"><label class="form-label" for="local">Local</label><input class="form-control" id="local" name="local" maxlength="255" value="{{ old('local', $convidado->local) }}"></div>
<div class="col-12 col-md-3"><label class="form-label" for="telefone_whatsapp">Telefone/WhatsApp</label><input class="form-control" id="telefone_whatsapp" name="telefone_whatsapp" maxlength="30" value="{{ old('telefone_whatsapp', $convidado->telefone_whatsapp) }}"></div>
@php($eventosSelecionados = array_map('intval', (array) old('eventos', $convidado->eventos->modelKeys())))
<div class="col-12 col-md-2"><label class="form-label" for="eventos">Evento *</label><select class="form-select" id="eventos" name="eventos[]" multiple required>@foreach($eventos as $evento)<option value="{{ $evento->id }}" @selected(in_array($evento->id, $eventosSelecionados, true))>{{ $evento->nome }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label fw-semibold" for="foto">Foto do convidado</label><div class="foto-upload-panel"><div class="row g-3 align-items-center"><div class="col-12 col-md-auto text-center"><img id="fotoPreview" class="foto-preview" src="{{$convidado->foto_nome?route('convidados.foto',$convidado->foto_nome):''}}" @if(!$convidado->foto_nome) style="display:none" @endif alt="Prévia da foto"><div id="fotoSemPreview" class="foto-preview bg-white d-inline-flex align-items-center justify-content-center text-secondary" @if($convidado->foto_nome) style="display:none!important" @endif><i class="bi bi-person fs-1" aria-hidden="true"></i></div></div><div class="col"><input class="form-control" id="foto" name="foto" type="file" accept="image/jpeg,image/png,image/webp"><div class="form-text mb-3">Escolha uma imagem JPG, PNG ou WebP de até 8 MB. Em seguida, ajuste o recorte quadrado.</div><div id="fotoColarArea" class="foto-colar-area rounded-3 p-3 d-flex align-items-center gap-3" tabindex="0" role="button" aria-label="Área para colar ou soltar uma foto" aria-describedby="fotoColarInstrucao"><i class="bi bi-clipboard-plus text-primary" aria-hidden="true"></i><div><div class="fw-semibold" id="fotoColarStatus">Cole uma imagem com Ctrl+V</div><div class="small text-secondary" id="fotoColarInstrucao">Clique nesta área antes de colar ou arraste uma imagem até aqui.</div></div></div><div id="fotoColarErro" class="text-danger small mt-2 d-none" role="alert"></div></div></div></div></div>
<div class="col-12 curriculo-field">
    <section class="card" aria-labelledby="curriculoTitulo">
        <div class="card-header"><h2 id="curriculoTitulo" class="h6 fw-semibold mb-0">Currículo</h2></div>
        <div class="card-body"><input type="hidden" id="curriculo" name="curriculo"><div class="curriculo-editor-wrapper"><div id="curriculoEditor"></div></div></div>
    </section>
</div>
<div class="col-12 descricao-field">
    <section class="card" aria-labelledby="descricaoTitulo">
        <div class="card-header"><h2 id="descricaoTitulo" class="h6 fw-semibold mb-0"><label for="descricao" class="mb-0">Descrição</label></h2></div>
        <div class="card-body"><textarea class="form-control" id="descricao" name="descricao" rows="4">{{ old('descricao', $convidado->descricao) }}</textarea></div>
    </section>
</div>
<div class="col-12"><label class="form-label fw-semibold">Redes sociais</label><div id="socialRows" class="d-grid gap-2 mb-2"></div><button type="button" id="addSocial" class="btn btn-sm btn-outline-primary"><i class="bi bi-plus-lg me-1"></i>Adicionar rede social</button></div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{route('convidados.index')}}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary">Salvar</button></div></div></div></form>@endsection
<div class="modal fade" id="cropModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Ajustar foto</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body text-center"><canvas id="cropCanvas" class="crop-canvas"></canvas><div class="small text-secondary mt-2">Arraste o quadro para escolher a área da foto.</div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button type="button" class="btn btn-primary" id="confirmCrop">Usar esta foto</button></div></div></div></div>
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script><script>
document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('convidadoForm');
$('#eventos').select2({theme:'bootstrap-5',width:'100%',placeholder:'Busque eventos',closeOnSelect:false,language:{noResults:()=> 'Nenhum evento encontrado'}});

const quill=new Quill('#curriculoEditor',{theme:'snow',modules:{toolbar:[['bold','italic','underline'],[{header:[1,2,3,false]}],[{list:'ordered'},{list:'bullet'}],['blockquote','clean']]}});quill.clipboard.dangerouslyPasteHTML(@json(old('curriculo',$convidado->curriculo??'')));form.addEventListener('submit',()=>document.getElementById('curriculo').value=quill.root.innerHTML);
const rows=document.getElementById('socialRows'),options=['Instagram','LinkedIn','Facebook','X','YouTube','Lattes','Site'];let index=0;const add=(item={})=>{const i=index++,row=document.createElement('div');row.className='social-row row g-2 align-items-end';row.innerHTML=`<div class="col-md-3"><label class="form-label small">Rede</label><select class="form-select" name="redes_sociais[${i}][rede]" required>${options.map(x=>`<option ${x===(item.rede||'')?'selected':''}>${x}</option>`).join('')}</select></div><div class="col-md-3"><label class="form-label small">Nome</label><input class="form-control" name="redes_sociais[${i}][nome]" required></div><div class="col-md-5"><label class="form-label small">Link</label><input type="url" class="form-control" name="redes_sociais[${i}][url]" placeholder="https://" required></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger w-100" title="Remover"><i class="bi bi-trash"></i></button></div>`;row.querySelector('[name$="[nome]"]').value=item.nome||'';row.querySelector('[name$="[url]"]').value=item.url||'';row.querySelector('button').onclick=()=>row.remove();rows.append(row)};document.getElementById('addSocial').onclick=()=>add();(@json(old('redes_sociais',$convidado->redes_sociais??[]))).forEach(add);
const input=document.getElementById('foto'),preview=document.getElementById('fotoPreview'),semPreview=document.getElementById('fotoSemPreview'),colarArea=document.getElementById('fotoColarArea'),colarStatus=document.getElementById('fotoColarStatus'),colarErro=document.getElementById('fotoColarErro'),canvas=document.getElementById('cropCanvas'),ctx=canvas.getContext('2d'),modal=new bootstrap.Modal('#cropModal');let imagem=null,area=null,arrastando=false,origem={};
const desenhar=()=>{if(!imagem)return;ctx.clearRect(0,0,canvas.width,canvas.height);const escala=Math.min(canvas.width/imagem.width,canvas.height/imagem.height),iw=imagem.width*escala,ih=imagem.height*escala,ix=(canvas.width-iw)/2,iy=(canvas.height-ih)/2;ctx.drawImage(imagem,ix,iy,iw,ih);ctx.fillStyle='rgba(0,0,0,.55)';ctx.beginPath();ctx.rect(0,0,canvas.width,canvas.height);ctx.rect(area.x,area.y,area.s,area.s);ctx.fill('evenodd');ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(area.x,area.y,area.s,area.s);area.imagem={ix,iy,iw,ih}};
const erroFoto=mensagem=>{colarErro.textContent=mensagem;colarErro.classList.remove('d-none')};
const abrirRecorte=arquivo=>{colarErro.classList.add('d-none');if(!arquivo)return;if(!['image/jpeg','image/png','image/webp'].includes(arquivo.type)){input.value='';erroFoto('Cole ou selecione somente imagens JPG, PNG ou WebP.');return}if(arquivo.size>8*1024*1024){input.value='';erroFoto('A imagem deve ter no máximo 8 MB.');return}colarStatus.textContent=`${arquivo.name||'Imagem colada'} — ${(arquivo.size/1024).toLocaleString('pt-BR',{maximumFractionDigits:1})} KB`;const leitor=new FileReader();leitor.onload=()=>{imagem=new Image();imagem.onerror=()=>erroFoto('Não foi possível abrir esta imagem.');imagem.onload=()=>{canvas.width=Math.min(600,Math.max(320,window.innerWidth-80));canvas.height=Math.min(460,canvas.width*.72);area={s:Math.min(canvas.width,canvas.height)*.78};area.x=(canvas.width-area.s)/2;area.y=(canvas.height-area.s)/2;desenhar();modal.show()};imagem.src=leitor.result};leitor.readAsDataURL(arquivo)};
const prepararArquivo=arquivo=>{if(!arquivo)return;try{const nome=arquivo.name&&arquivo.name!=='image.png'?arquivo.name:`foto-colada-${Date.now()}.${arquivo.type==='image/webp'?'webp':arquivo.type==='image/jpeg'?'jpg':'png'}`,copia=new File([arquivo],nome,{type:arquivo.type}),transfer=new DataTransfer();transfer.items.add(copia);input.files=transfer.files;input.dispatchEvent(new Event('change'))}catch(erro){erroFoto('Seu navegador não permitiu preparar a imagem colada.')}};
input.addEventListener('change',()=>abrirRecorte(input.files[0]));
colarArea.addEventListener('click',()=>colarArea.focus());
colarArea.addEventListener('paste',evento=>{evento.preventDefault();const arquivo=Array.from(evento.clipboardData?.files||[]).find(item=>item.type.startsWith('image/'))||Array.from(evento.clipboardData?.items||[]).find(item=>item.kind==='file'&&item.type.startsWith('image/'))?.getAsFile();if(!arquivo){erroFoto('A área de transferência não contém uma imagem.');return}prepararArquivo(arquivo)});
['dragenter','dragover'].forEach(tipo=>colarArea.addEventListener(tipo,evento=>{evento.preventDefault();colarArea.classList.add('arrastando')}));['dragleave','drop'].forEach(tipo=>colarArea.addEventListener(tipo,evento=>{evento.preventDefault();colarArea.classList.remove('arrastando')}));colarArea.addEventListener('drop',evento=>{const arquivo=Array.from(evento.dataTransfer?.files||[]).find(item=>item.type.startsWith('image/'));if(!arquivo){erroFoto('Solte somente uma imagem JPG, PNG ou WebP.');return}prepararArquivo(arquivo)});
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;if(x>=area.x&&x<=area.x+area.s&&y>=area.y&&y<=area.y+area.s){arrastando=true;origem={x,y,ax:area.x,ay:area.y};canvas.setPointerCapture(e.pointerId)}});canvas.addEventListener('pointermove',e=>{if(!arrastando)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;area.x=Math.max(area.imagem.ix,Math.min(area.imagem.ix+area.imagem.iw-area.s,origem.ax+x-origem.x));area.y=Math.max(area.imagem.iy,Math.min(area.imagem.iy+area.imagem.ih-area.s,origem.ay+y-origem.y));desenhar()});canvas.addEventListener('pointerup',()=>arrastando=false);
document.getElementById('confirmCrop').onclick=()=>{const scale=imagem.width/area.imagem.iw,out=document.createElement('canvas');out.width=out.height=600;out.getContext('2d').drawImage(imagem,(area.x-area.imagem.ix)*scale,(area.y-area.imagem.iy)*scale,area.s*scale,area.s*scale,0,0,600,600);out.toBlob(blob=>{const arquivo=new File([blob],'foto.jpg',{type:'image/jpeg'}),transfer=new DataTransfer();transfer.items.add(arquivo);input.files=transfer.files;preview.src=URL.createObjectURL(blob);preview.style.display='block';semPreview.style.setProperty('display','none','important');colarStatus.textContent='Recorte pronto para salvar';modal.hide()},'image/jpeg',.9)};
});</script>@endpush
