@extends('layouts.app')
@section('title',$convidado->exists?'Editar convidado':'Novo convidado')
@push('styles')<link href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" rel="stylesheet"><style>.curriculo-field,.descricao-field{position:relative;clear:both}.curriculo-editor-wrapper{overflow:hidden;border-radius:.5rem;background:#fff}.curriculo-editor-wrapper .ql-toolbar{border-radius:.5rem .5rem 0 0}.curriculo-editor-wrapper .ql-container{height:auto;max-height:420px;border-radius:0 0 .5rem .5rem}.curriculo-editor-wrapper .ql-editor{min-height:180px;max-height:380px;overflow-y:auto}.descricao-field{margin-top:.75rem}.social-row{background:#f8fafc;border:1px solid #e9ecef;border-radius:.6rem;padding:.75rem}</style>@endpush
@section('content')
<div class="mb-4"><h1 class="page-title">{{$convidado->exists?'Editar convidado':'Novo convidado'}}</h1><p class="page-description mb-0">Preencha os dados do professor convidado.</p></div>
<form id="convidadoForm" method="POST" action="{{$convidado->exists?route('convidados.update',$convidado):route('convidados.store')}}">@csrf @if($convidado->exists)@method('PUT')@endif
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">Dados do convidado</h2></div><div class="card-body p-4">@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif<div class="row g-3">
<div class="col-md-6"><label class="form-label" for="nome">Nome *</label><input class="form-control" id="nome" name="nome" required value="{{old('nome',$convidado->nome)}}"></div><div class="col-md-6"><label class="form-label" for="sobrenome">Sobrenome</label><input class="form-control" id="sobrenome" name="sobrenome" value="{{old('sobrenome',$convidado->sobrenome)}}"></div>
@php($outra=$convidado->titulacao&&!in_array($convidado->titulacao,$titulacoes,true))
<div class="col-md-4"><label class="form-label" for="titulacao_opcao">Titulação</label><select class="form-select" id="titulacao_opcao" name="titulacao_opcao"><option value="">Não informada</option>@foreach($titulacoes as $item)<option value="{{$item}}" @selected(old('titulacao_opcao',$outra?'outra':$convidado->titulacao)===$item)>{{$item}}</option>@endforeach<option value="outra" @selected(old('titulacao_opcao',$outra?'outra':null)==='outra')>Outra</option></select></div>
<div id="outraTitulacaoGrupo" class="col-md-4 d-none"><label class="form-label" for="titulacao_outra">Outra titulação</label><input class="form-control" id="titulacao_outra" name="titulacao_outra" value="{{old('titulacao_outra',$outra?$convidado->titulacao:null)}}"></div>
<div class="col-md-4"><label class="form-label" for="local">Local</label><input class="form-control" id="local" name="local" value="{{old('local',$convidado->local)}}"></div><div class="col-md-4"><label class="form-label" for="telefone_whatsapp">Telefone/WhatsApp</label><input class="form-control" id="telefone_whatsapp" name="telefone_whatsapp" maxlength="30" value="{{old('telefone_whatsapp',$convidado->telefone_whatsapp)}}"></div><div class="col-md-4"><label class="form-label" for="email">E-mail</label><input type="email" class="form-control" id="email" name="email" value="{{old('email',$convidado->email)}}"></div>
<div class="col-12 curriculo-field"><label class="form-label fw-semibold">Currículo</label><input type="hidden" id="curriculo" name="curriculo"><div class="curriculo-editor-wrapper"><div id="curriculoEditor"></div></div></div>
<div class="col-12 descricao-field"><label class="form-label fw-semibold" for="descricao">Descrição</label><textarea class="form-control" id="descricao" name="descricao" rows="4">{{old('descricao',$convidado->descricao)}}</textarea></div>
<div class="col-12"><label class="form-label fw-semibold">Redes sociais</label><div id="socialRows" class="d-grid gap-2 mb-2"></div><button type="button" id="addSocial" class="btn btn-sm btn-outline-primary"><i class="bi bi-plus-lg me-1"></i>Adicionar rede social</button></div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{route('convidados.index')}}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary">Salvar</button></div></div></div></form>@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script><script>
document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('convidadoForm'),select=document.getElementById('titulacao_opcao'),group=document.getElementById('outraTitulacaoGrupo'),other=document.getElementById('titulacao_outra');const toggle=()=>{const show=select.value==='outra';group.classList.toggle('d-none',!show);other.required=show};select.onchange=toggle;toggle();
const quill=new Quill('#curriculoEditor',{theme:'snow',modules:{toolbar:[['bold','italic','underline'],[{header:[1,2,3,false]}],[{list:'ordered'},{list:'bullet'}],['blockquote','clean']]}});quill.clipboard.dangerouslyPasteHTML(@json(old('curriculo',$convidado->curriculo??'')));form.addEventListener('submit',()=>document.getElementById('curriculo').value=quill.root.innerHTML);
const rows=document.getElementById('socialRows'),options=['Instagram','LinkedIn','Facebook','X','YouTube','Lattes','Site'];let index=0;const add=(item={})=>{const i=index++,row=document.createElement('div');row.className='social-row row g-2 align-items-end';row.innerHTML=`<div class="col-md-3"><label class="form-label small">Rede</label><select class="form-select" name="redes_sociais[${i}][rede]" required>${options.map(x=>`<option ${x===(item.rede||'')?'selected':''}>${x}</option>`).join('')}</select></div><div class="col-md-3"><label class="form-label small">Nome</label><input class="form-control" name="redes_sociais[${i}][nome]" required></div><div class="col-md-5"><label class="form-label small">Link</label><input type="url" class="form-control" name="redes_sociais[${i}][url]" placeholder="https://" required></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger w-100" title="Remover"><i class="bi bi-trash"></i></button></div>`;row.querySelector('[name$="[nome]"]').value=item.nome||'';row.querySelector('[name$="[url]"]').value=item.url||'';row.querySelector('button').onclick=()=>row.remove();rows.append(row)};document.getElementById('addSocial').onclick=()=>add();(@json(old('redes_sociais',$convidado->redes_sociais??[]))).forEach(add);
});</script>@endpush
