@extends('layouts.app')
@section('title','Convidados')
@push('styles')<link href="https://cdn.datatables.net/2.3.2/css/dataTables.bootstrap5.min.css" rel="stylesheet">@endpush
@section('content')
<div class="mb-4 d-flex justify-content-between gap-3"><div><h1 class="page-title">Professores convidados</h1><p class="page-description mb-0">Gerencie os convidados dos eventos.</p></div>@if(app(\App\Services\GiPermissionService::class)->permite('convidados.criar'))<a href="{{route('convidados.create')}}" class="btn btn-primary align-self-start"><i class="bi bi-plus-lg me-1"></i>Novo convidado</a>@endif</div>
@if(session('status'))<div class="alert alert-success">{{session('status')}}</div>@endif<div id="feedback" class="alert alert-danger d-none"></div>
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">Convidados cadastrados</h2></div><div class="card-body p-0"><div class="table-responsive"><table id="convidadosTable" class="table table-hover align-middle w-100 mb-0"><thead><tr><th>ID</th><th>Nome</th><th>Sobrenome</th><th>Titulação</th><th>Local</th><th>WhatsApp</th><th>E-mail</th><th>Criação</th><th>Alteração</th><th data-dt-order="disable">Ações</th></tr></thead></table></div></div></div>@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.bootstrap5.min.js"></script><script>
document.addEventListener('DOMContentLoaded',()=>{const table=new DataTable('#convidadosTable',{processing:true,serverSide:true,order:[[0,'desc']],pageLength:@json($estadoTabela['por_pagina']),displayStart:@json(($estadoTabela['page']-1)*$estadoTabela['por_pagina']),search:{search:@json($estadoTabela['pesquisar'])},ajax:@json(route('convidados.dados',[],false)),columns:[{data:'id'},{data:'nome'},{data:'sobrenome'},{data:'titulacao'},{data:'local'},{data:'telefone_whatsapp'},{data:'email'},{data:'created_at'},{data:'updated_at'},{data:'acoes',orderable:false,searchable:false}],language:{processing:'Carregando...',emptyTable:'Nenhum convidado cadastrado.',info:'Exibindo _START_ a _END_ de _TOTAL_ convidados',infoEmpty:'Nenhum convidado encontrado',lengthMenu:'Exibir _MENU_ registros',search:'Pesquisar:',zeroRecords:'Nenhum convidado encontrado.',paginate:{next:'Próxima',previous:'Anterior'}}});document.getElementById('convidadosTable').onclick=async e=>{const b=e.target.closest('[data-delete-url]');if(!b||!confirm('Excluir este convidado?'))return;b.disabled=true;try{const r=await fetch(b.dataset.deleteUrl,{method:'DELETE',credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':@json(csrf_token())}});const p=await r.json();if(!r.ok)throw new Error(p.message);table.ajax.reload(null,false)}catch(x){const f=document.getElementById('feedback');f.textContent=x.message||'Falha ao excluir.';f.classList.remove('d-none');b.disabled=false}}});
</script>@endpush
