@extends('layouts.app')
@section('title','Visualizar convidado')
@section('content')
<div class="mb-4 d-flex justify-content-between gap-3"><div><h1 class="page-title">Visualizar convidado</h1><p class="page-description mb-0">Dados do professor convidado.</p></div><div class="d-flex gap-2"><a href="{{route('convidados.index')}}" class="btn btn-outline-secondary">Voltar</a>@if(app(\App\Services\GiPermissionService::class)->permite('convidados.editar'))<a href="{{route('convidados.edit',$convidado)}}" class="btn btn-primary">Editar</a>@endif</div></div>
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">{{$convidado->nome}} {{$convidado->sobrenome}}</h2></div><div class="card-body p-4"><div class="row g-4">
<div class="col-md-4"><div class="small fw-bold text-secondary">Titulação</div>{{$convidado->titulacao?:'—'}}</div><div class="col-md-4"><div class="small fw-bold text-secondary">Local</div>{{$convidado->local?:'—'}}</div><div class="col-md-4"><div class="small fw-bold text-secondary">Telefone/WhatsApp</div>{{$convidado->telefone_whatsapp?:'—'}}</div><div class="col-md-4"><div class="small fw-bold text-secondary">E-mail</div>{{$convidado->email?:'—'}}</div><div class="col-12"><div class="small fw-bold text-secondary mb-1">Descrição</div><div class="text-break">{{$convidado->descricao?:'—'}}</div></div>
<div class="col-12"><div class="small fw-bold text-secondary mb-1">Currículo</div><div class="border rounded p-3 bg-light">{!!$convidado->curriculo?:'—'!!}</div></div>
<div class="col-12"><div class="small fw-bold text-secondary mb-2">Redes sociais</div><div class="d-flex flex-wrap gap-2">@forelse($convidado->redes_sociais??[] as $rede)<a class="btn btn-sm btn-outline-primary" href="{{$rede['url']}}" target="_blank" rel="noopener noreferrer">{{$rede['rede']}}: {{$rede['nome']}}</a>@empty<span class="text-secondary">—</span>@endforelse</div></div>
<div class="col-md-6"><div class="small fw-bold text-secondary">Criado em</div>{{$convidado->created_at?->format('d/m/Y H:i')??'—'}}</div><div class="col-md-6"><div class="small fw-bold text-secondary">Alterado em</div>{{$convidado->updated_at?->format('d/m/Y H:i')??'—'}}</div>
</div></div></div>@endsection
