@extends('layouts.app')

@section('title', $transmissao->titulo.' — Ao vivo')

@push('styles')
<style>
.sala-video{background:#101114;min-height:100vh;color:#fff}.sala-palco{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:1rem}.sala-tile{background:#22252b;border-radius:.75rem;overflow:hidden;min-height:190px;position:relative}.sala-tile video{display:block;width:100%;height:100%;min-height:190px;object-fit:cover;background:#050505}.sala-tile__nome{position:absolute;bottom:.5rem;left:.5rem;background:rgba(0,0,0,.7);border-radius:.25rem;padding:.2rem .45rem;font-size:.875rem}.sala-vazia{grid-column:1/-1;color:#aeb4bc;text-align:center;padding:4rem 1rem;border:1px dashed #555;border-radius:.75rem}.sala-controles{position:sticky;bottom:0;background:rgba(16,17,20,.96);padding:1rem 0}.sala-controles .btn{min-width:130px}
</style>
@endpush

@section('content')
<div class="sala-video">
    <div class="container py-4 py-md-5">
        <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h1 class="h3 mb-1">{{ $transmissao->titulo }}</h1>@if($transmissao->descricao)<p class="text-white-50 mb-0">{{ $transmissao->descricao }}</p>@endif</div><span class="badge text-bg-danger"><i class="bi bi-broadcast me-1"></i>Ao vivo</span></div>
        <div id="entrada" class="card text-dark mx-auto" style="max-width:700px"><div class="card-body p-4"><h2 class="h5">Entrar na sala</h2><p class="text-muted small mb-1">Seu navegador solicitará acesso à câmera e ao microfone. Você poderá compartilhar a tela depois de entrar.</p><p class="text-muted small"><i class="bi bi-browser-chrome me-1"></i>Para uma melhor experiência, recomendamos utilizar o Google Chrome.</p><form id="formEntrada"><label class="form-label" for="nome">Seu nome</label><input class="form-control" id="nome" name="nome" maxlength="80" minlength="2" required autocomplete="name" autofocus><div id="erroEntrada" class="text-danger small mt-3 d-none"></div><button id="verConfiguracao" class="btn btn-link btn-sm px-0 d-none" type="button" aria-expanded="false">Ver configuração</button><div id="configuracaoLiveKit" class="alert alert-secondary small mt-2 d-none"><h3 class="h6">Configuração do servidor de videoconferência</h3><ol class="mb-2"><li>Instale Docker no Linux.</li><li>Para testar localmente, execute <code>docker run --rm --network host livekit/livekit-server --dev --bind 0.0.0.0</code>.</li><li>Em produção, abra TCP 7880, TCP 7881 e UDP 50000-60000; configure domínio HTTPS e TURN.</li><li>No <code>.env</code> desta aplicação, defina <code>LIVEKIT_URL=wss://livekit.seudominio.com</code>, <code>LIVEKIT_API_KEY=devkey</code> e <code>LIVEKIT_API_SECRET=secret</code>.</li><li>Execute <code>php artisan config:clear</code>.</li></ol><p class="mb-0">Em produção, substitua <code>devkey</code> e <code>secret</code> por valores longos e exclusivos.</p></div><button class="btn btn-primary w-100 mt-3" type="submit"><i class="bi bi-camera-video me-1"></i>Entrar</button></form></div></div>
        <div id="sala" class="d-none"><div id="statusSala" class="text-white-50 small mb-3">Conectando…</div><div id="audioRemoto" class="d-none"></div><div class="sala-palco" id="palco"><div class="sala-vazia" id="palcoVazio">Aguardando câmeras e compartilhamentos de tela.</div></div><div class="sala-controles mt-4"><div class="d-flex flex-wrap justify-content-center gap-2"><button class="btn btn-outline-light" id="camera" type="button"><i class="bi bi-camera-video me-1"></i>Desligar câmera</button><button class="btn btn-outline-light" id="microfone" type="button"><i class="bi bi-mic me-1"></i>Silenciar</button><button class="btn btn-primary" id="tela" type="button"><i class="bi bi-display me-1"></i>Compartilhar tela</button><button class="btn btn-outline-danger" id="sair" type="button"><i class="bi bi-box-arrow-right me-1"></i>Sair</button></div></div></div>
    </div>
</div>
@endsection

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/livekit-client@2.15.7/dist/livekit-client.umd.min.js"></script>
<script>
(() => {
    const entrada=document.getElementById('entrada'), sala=document.getElementById('sala'), form=document.getElementById('formEntrada'), erro=document.getElementById('erroEntrada'), configuracao=document.getElementById('configuracaoLiveKit'), verConfiguracao=document.getElementById('verConfiguracao'), palco=document.getElementById('palco'), vazio=document.getElementById('palcoVazio'), status=document.getElementById('statusSala');
    const botoes={camera:document.getElementById('camera'),microfone:document.getElementById('microfone'),tela:document.getElementById('tela'),sair:document.getElementById('sair')}; let room, camera=true, microfone=true, tela=false;
    const csrf='{{ csrf_token() }}';
    const mostrarErro=(texto,exibirConfiguracao=false)=>{erro.replaceChildren(document.createTextNode(texto));if(/could not establish pc connection/i.test(texto)){const recomendacao=document.createElement('span');recomendacao.className='ms-1';recomendacao.textContent='Recomendamos utilizar o Google Chrome para entrar na sala.';erro.append(recomendacao)}erro.classList.remove('d-none');verConfiguracao.classList.toggle('d-none',!exibirConfiguracao)};
    const idTile=(participante, publicacao)=>`tile-${participante.identity}-${publicacao.trackSid||publicacao.sid||publicacao.source}`.replace(/[^a-zA-Z0-9_-]/g,'_');
    function mostrarTrack(track, publicacao, participante){const id=idTile(participante,publicacao);if(document.getElementById(id))return;if(track.kind==='audio'){if(participante.isLocal)return;const audio=track.attach();audio.id=id;audio.autoplay=true;document.getElementById('audioRemoto').append(audio);return}if(track.kind!=='video')return;vazio?.remove();const tile=document.createElement('div');tile.className='sala-tile';tile.id=id;const video=track.attach();video.autoplay=true;video.playsInline=true;if(participante.isLocal)video.muted=true;tile.append(video);const nome=document.createElement('span');nome.className='sala-tile__nome';nome.textContent=`${participante.name||'Participante'}${publicacao.source==='screen_share'?' — tela':''}`;tile.append(nome);palco.append(tile)}
    function removerTrack(publicacao, participante){document.getElementById(idTile(participante,publicacao))?.remove();if(!palco.querySelector('.sala-tile'))palco.append(vazio||Object.assign(document.createElement('div'),{className:'sala-vazia',textContent:'Aguardando câmeras e compartilhamentos de tela.'}))}
    function atualizarControles(){botoes.camera.innerHTML=`<i class="bi bi-camera-video${camera?'':'-off'} me-1"></i>${camera?'Desligar câmera':'Ligar câmera'}`;botoes.microfone.innerHTML=`<i class="bi bi-mic${microfone?'':'-mute'} me-1"></i>${microfone?'Silenciar':'Ligar microfone'}`;botoes.tela.innerHTML=`<i class="bi bi-display me-1"></i>${tela?'Parar compartilhamento':'Compartilhar tela'}`}
    async function entrar(nome){const resposta=await fetch('{{ route('transmissoes.entrar', ['transmissao' => $transmissao->hash_publico]) }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({nome})});const dados=await resposta.json();if(!resposta.ok)throw Object.assign(new Error(dados.message||'Não foi possível entrar na sala.'),{configuracao:!!dados.configuracao});room=new LivekitClient.Room();room.on(LivekitClient.RoomEvent.TrackSubscribed,mostrarTrack);room.on(LivekitClient.RoomEvent.TrackUnsubscribed,removerTrack);room.on(LivekitClient.RoomEvent.TrackPublished,(pub,participante)=>{if(pub.track)mostrarTrack(pub.track,pub,participante)});room.on(LivekitClient.RoomEvent.ParticipantDisconnected,(participante)=>{document.querySelectorAll(`[id^="tile-${participante.identity.replace(/[^a-zA-Z0-9_-]/g,'_')}-"]`).forEach(e=>e.remove())});room.on(LivekitClient.RoomEvent.Disconnected,()=>{status.textContent='Você saiu da sala.'});await room.connect(dados.url,dados.token);await room.localParticipant.setCameraEnabled(true);await room.localParticipant.setMicrophoneEnabled(true);room.localParticipant.trackPublications.forEach(pub=>{if(pub.track)mostrarTrack(pub.track,pub,room.localParticipant)});status.textContent='Conectado. Sua câmera e seu microfone estão ativos.';entrada.classList.add('d-none');sala.classList.remove('d-none');atualizarControles()}
    form.addEventListener('submit',async e=>{e.preventDefault();erro.classList.add('d-none');const botao=form.querySelector('button[type="submit"]');botao.disabled=true;try{await entrar(document.getElementById('nome').value.trim())}catch(ex){mostrarErro(ex.message,ex.configuracao);botao.disabled=false}});verConfiguracao.addEventListener('click',()=>{const oculto=configuracao.classList.toggle('d-none');verConfiguracao.textContent=oculto?'Ver configuração':'Ocultar configuração';verConfiguracao.setAttribute('aria-expanded',String(!oculto))});
    botoes.camera.addEventListener('click',async()=>{camera=!camera;await room.localParticipant.setCameraEnabled(camera);atualizarControles()});botoes.microfone.addEventListener('click',async()=>{microfone=!microfone;await room.localParticipant.setMicrophoneEnabled(microfone);atualizarControles()});botoes.tela.addEventListener('click',async()=>{try{tela=!tela;await room.localParticipant.setScreenShareEnabled(tela);atualizarControles()}catch(ex){tela=false;atualizarControles();status.textContent='Não foi possível compartilhar a tela: '+ex.message}});botoes.sair.addEventListener('click',()=>{room?.disconnect();sala.classList.add('d-none');entrada.classList.remove('d-none')});
})();
</script>
@endpush
