@extends('layouts.app')

@section('title', 'Tutorial do servidor de streaming')

@push('styles')
<style>.tutorial-livekit{max-width:1000px}.tutorial-livekit pre{background:#15191f;color:#e8edf2;border-radius:.6rem;padding:1rem;white-space:pre-wrap}.tutorial-livekit code{color:inherit}.tutorial-livekit h2{margin-top:2.25rem}</style>
@endpush

@section('content')
<div class="container py-4 tutorial-livekit">
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h1 class="page-title">Tutorial: servidor de videoconferência</h1><p class="page-description mb-0">Instalação do LiveKit para as salas ao vivo. A futura saída para YouTube exige Egress/Ingress, em etapa separada.</p></div><a class="btn btn-outline-secondary" href="{{ route('transmissoes.configuracao') }}"><i class="bi bi-arrow-left me-1"></i>Voltar à configuração</a></div>
<div class="alert alert-warning"><strong>Produção:</strong> use domínio próprio, certificado TLS válido e segredos exclusivos. Não exponha a API Secret em navegador, repositório ou captura de tela.</div>
<section><h2 class="h4">1. Ambiente</h2><p>Para desenvolvimento local use <code>ws://localhost:7880</code>. Para participantes externos, use <code>livekit.exemplo.com</code> e a URL <code>wss://livekit.exemplo.com</code>. Uma página HTTPS exige WebSocket seguro (<code>wss://</code>).</p></section>
<section><h2 class="h4">2. Docker e usuário sem root</h2><p>Instale Docker Engine e o plugin Compose pelo repositório oficial do Docker. Valide a instalação:</p><pre><code>sudo docker run --rm hello-world<br>docker compose version</code></pre><p>Para operar sem root, inclua somente usuários administrativos confiáveis no grupo Docker. Saia e entre novamente na sessão, ou use <code>newgrp docker</code>.</p><pre><code>sudo usermod -aG docker $USER<br>newgrp docker<br>docker ps</code></pre><div class="alert alert-info small">O grupo <code>docker</code> equivale a privilégio administrativo no host.</div></section>
<section><h2 class="h4">3. Teste local rápido</h2><p>Este modo usa <code>devkey</code>/<code>secret</code> e não deve ser exposto à internet.</p><pre><code>docker run --rm --network host livekit/livekit-server --dev --bind 0.0.0.0</code></pre><p>Na configuração desta aplicação informe URL <code>ws://localhost:7880</code>, API Key <code>devkey</code> e API Secret <code>secret</code>. Entre em duas abas para testar câmera e áudio.</p></section>
<section><h2 class="h4">4. Docker em servidor</h2><p>Crie <code>/opt/livekit/livekit.yaml</code>, usando chaves longas e exclusivas:</p><pre><code>port: 7880<br>rtc:<br>  tcp_port: 7881<br>  port_range_start: 50000<br>  port_range_end: 50100<br>  use_external_ip: true<br>room:<br>  enable_remote_unmute: true<br>keys:<br>  SUA_API_KEY: SUA_API_SECRET_LONGA_E_ALEATORIA</code></pre><p>Inicie com rede do host, que simplifica o tráfego UDP do WebRTC:</p><pre><code>sudo mkdir -p /opt/livekit<br>sudo docker run -d --name livekit --restart unless-stopped --network host -v /opt/livekit/livekit.yaml:/etc/livekit.yaml:ro livekit/livekit-server:latest --config /etc/livekit.yaml<br>sudo docker logs -f livekit</code></pre></section>
<section><h2 class="h4">5. Portainer</h2><p>Em <strong>Stacks → Add stack</strong>, publique uma stack com <code>network_mode: host</code>. Crie o YAML do passo anterior no host antes de publicar.</p><pre><code>services:<br>  livekit:<br>    image: livekit/livekit-server:latest<br>    restart: unless-stopped<br>    network_mode: host<br>    volumes:<br>      - /opt/livekit/livekit.yaml:/etc/livekit.yaml:ro<br>    command: --config /etc/livekit.yaml</code></pre><p>Depois, confira <strong>Containers → livekit → Logs</strong>. Não use mapeamento aleatório para a faixa UDP.</p></section>
<section><h2 class="h4">6. Domínio, HTTPS e WSS</h2><p>Crie um registro DNS <code>A</code> de <code>livekit.seudominio.com</code> para o IP público. Coloque a porta 7880 atrás de Nginx, Caddy ou balanceador com certificado confiável. O proxy termina TLS em 443 e encaminha WebSocket para <code>http://127.0.0.1:7880</code>, preservando <code>Upgrade</code> e <code>Connection</code>.</p><p>Para produção, o gerador oficial cria Docker Compose com Caddy, TLS e TURN:</p><pre><code>docker pull livekit/generate<br>docker run --rm -it -v "$PWD:/output" livekit/generate</code></pre></section>
<section><h2 class="h4">7. Firewall</h2><p>Libere 80/443 para HTTPS e certificado, 7881/TCP e a faixa UDP configurada. Se usar TURN integrado, libere também 3478/UDP. Repita as regras no firewall do provedor.</p><pre><code># UFW (Ubuntu)<br>sudo ufw allow 80/tcp<br>sudo ufw allow 443/tcp<br>sudo ufw allow 7881/tcp<br>sudo ufw allow 3478/udp<br>sudo ufw allow 50000:50100/udp<br><br># firewalld (RHEL/Rocky/AlmaLinux)<br>sudo firewall-cmd --permanent --add-service=http<br>sudo firewall-cmd --permanent --add-service=https<br>sudo firewall-cmd --permanent --add-port=7881/tcp<br>sudo firewall-cmd --permanent --add-port=3478/udp<br>sudo firewall-cmd --permanent --add-port=50000-50100/udp<br>sudo firewall-cmd --reload</code></pre></section>
<section><h2 class="h4">8. Preencher a aplicação</h2><ol><li>Abra <strong>Transmissão → Configuração</strong>.</li><li>Use <code>wss://livekit.seudominio.com</code> em produção ou <code>ws://localhost:7880</code> localmente.</li><li>Copie API Key e API Secret da seção <code>keys</code> do YAML.</li><li>Salve e teste em duas redes diferentes.</li></ol><p><code>room.enable_remote_unmute: true</code> permite que o administrador reative uma mídia silenciada. Sem isso, a reativação costuma ser bloqueada por privacidade.</p></section>
<section><h2 class="h4">9. Testes e mensagens de erro</h2><table class="table table-striped align-middle"><thead><tr><th>Sintoma</th><th>Ação</th></tr></thead><tbody><tr><td><code>videoconferência ainda não está disponível</code></td><td>Confira URL, API Key, Secret e <code>docker logs livekit</code>.</td></tr><tr><td><code>could not establish pc connection</code></td><td>Libere UDP e 7881/TCP no host e no provedor; teste fora da VPN; configure TURN para redes restritas.</td></tr><tr><td>Erro de certificado ou WebSocket fecha</td><td>Use <code>wss://</code>, certificado confiável e proxy com suporte a Upgrade.</td></tr><tr><td>Câmera abre, mas participantes não se veem</td><td>Confirme DNS/IP público, <code>rtc.use_external_ip: true</code> e a faixa UDP.</td></tr><tr><td>Erro 401/credenciais inválidas</td><td>Key e Secret da aplicação devem coincidir com o YAML; reinicie após alterar o arquivo.</td></tr><tr><td>Administrador não reativa mídia</td><td>Ative <code>room.enable_remote_unmute: true</code> e reinicie o LiveKit.</td></tr></tbody></table><pre><code>sudo docker ps<br>sudo docker logs --tail 200 livekit<br>curl -I http://127.0.0.1:7880<br>ss -lntup | grep -E '7880|7881|3478'</code></pre></section>
<p class="small text-secondary mt-4">Referências: <a href="https://docs.livekit.io/transport/self-hosting/vm/" target="_blank" rel="noopener">implantação em VM</a>, <a href="https://docs.livekit.io/transport/self-hosting/ports-firewall/" target="_blank" rel="noopener">portas e firewall</a> e <a href="https://docs.livekit.io/transport/self-hosting/local/" target="_blank" rel="noopener">teste local</a>.</p>
</div>
@endsection
