@php($tipoAtividade = old('tipo', $atividade?->tipo ?? 'somente_inscricao'))
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">Dados da atividade</h2></div><div class="card-body p-4"><div class="row g-4">
<div class="col-12 col-lg-3"><label class="form-label fw-semibold" for="tipo_atividade">Tipo</label>
<select class="form-select @error('tipo') is-invalid @enderror" id="tipo_atividade" name="tipo" required>
<option value="somente_inscricao" @selected($tipoAtividade === 'somente_inscricao')>Somente inscrição</option>
<option value="atividade_evento" @selected($tipoAtividade === 'atividade_evento')>Atividade do Evento</option>
</select>@error('tipo')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-12 col-lg-9"><label class="form-label fw-semibold" for="nome">Nome *</label><input class="form-control @error('nome') is-invalid @enderror" id="nome" name="nome" maxlength="255" required value="{{old('nome',$atividade?->nome)}}">@error('nome')<div class="invalid-feedback">{{$message}}</div>@enderror</div>
<div class="col-12 col-lg-4"><label class="form-label fw-semibold" for="evento_id">Evento *</label><select class="form-select @error('evento_id') is-invalid @enderror" id="evento_id" name="evento_id" required><option value=""></option>@foreach($eventos as $evento)<option value="{{$evento->id}}" @selected((int)old('evento_id',$atividade?->evento_id)===$evento->id)>{{$evento->nome}}</option>@endforeach</select>@error('evento_id')<div class="invalid-feedback">{{$message}}</div>@enderror</div>
<div class="col-12 col-lg-4" data-campo-atividade @if($tipoAtividade === 'somente_inscricao') hidden @endif><label class="form-label fw-semibold" for="categoria_id">Categoria</label><select class="form-select @error('categoria_id') is-invalid @enderror" id="categoria_id" name="categoria_id" @disabled($tipoAtividade === 'somente_inscricao')><option value="">Sem categoria</option>@foreach($categorias as $categoria)<option value="{{$categoria->id}}" @selected((int)old('categoria_id',$atividade?->categoria_id)===$categoria->id)>{{$categoria->nome}}</option>@endforeach</select>@error('categoria_id')<div class="invalid-feedback">{{$message}}</div>@enderror</div>
<div class="col-12 col-lg-2"><label class="form-label fw-semibold" for="ativo">Status *</label><select class="form-select" id="ativo" name="ativo"><option value="1" @selected((int)old('ativo',isset($atividade)?(int)$atividade->ativo:1)===1)>Ativo</option><option value="0" @selected((int)old('ativo',isset($atividade)?(int)$atividade->ativo:1)===0)>Inativo</option></select></div>
<div class="col-12 col-md-4" data-campo-atividade @if($tipoAtividade === 'somente_inscricao') hidden @endif><label class="form-label fw-semibold" for="modalidade">Modalidade</label><select class="form-select @error('modalidade') is-invalid @enderror" id="modalidade" name="modalidade" @disabled($tipoAtividade === 'somente_inscricao')><option value="">Selecione...</option><option value="ead" @selected(old('modalidade',$atividade?->modalidade)==='ead')>EAD</option><option value="presencial" @selected(old('modalidade',$atividade?->modalidade)==='presencial')>Presencial</option></select>@error('modalidade')<div class="invalid-feedback">{{$message}}</div>@enderror</div>
<div class="col-12 col-md-4"><label class="form-label fw-semibold" for="data_inicio">Data de início</label><input type="datetime-local" class="form-control @error('data_inicio') is-invalid @enderror" id="data_inicio" name="data_inicio" value="{{old('data_inicio',$atividade?->data_inicio?->format('Y-m-d\TH:i'))}}">@error('data_inicio')<div class="invalid-feedback">{{$message}}</div>@enderror</div>
<div class="col-12 col-md-4"><label class="form-label fw-semibold" for="data_fim">Data de fim</label><input type="datetime-local" class="form-control @error('data_fim') is-invalid @enderror" id="data_fim" name="data_fim" value="{{old('data_fim',$atividade?->data_fim?->format('Y-m-d\TH:i'))}}">@error('data_fim')<div class="invalid-feedback">{{$message}}</div>@enderror</div>
</div></div></div>
@if(app(\App\Services\GiPermissionService::class)->permite('atividade.personalizar'))
@include('atividades.partials.personalizacao')
@endif
<div class="mt-4 d-flex justify-content-end gap-2"><a href="{{route('atividades.index')}}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary"><i class="bi bi-check-lg me-2"></i>Salvar</button></div>
@push('scripts')
<script src="{{ asset('tipo-atividade.js') }}?v={{ filemtime(public_path('tipo-atividade.js')) }}" defer></script>
@endpush
