@extends('layouts.app')
@section('title','Construtor de formulário')
@section('content')
<div class="mb-4 d-flex flex-wrap justify-content-between align-items-start gap-3"><div><h1 class="page-title">Formulário de inscrições</h1><p class="page-description mb-0">{{ $atividade->nome }}</p></div><a href="{{ route('atividades.index') }}" class="btn btn-outline-secondary">Voltar</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@error('formulario')<div class="alert alert-danger">{{ $message }}</div>@enderror
<form method="POST" action="{{ route('atividades.formulario.salvar',$atividade) }}" id="formBuilder">@csrf<input type="hidden" name="formulario" id="formularioJson">
<div class="card content-card mb-4"><div class="card-header"><h2 class="h5 fw-bold mb-0">Configuração</h2></div><div class="card-body"><div class="row g-3">
<div class="col-md-6"><label class="form-label">Título</label><input id="titulo" class="form-control"></div><div class="col-md-6"><label class="form-label">Subtítulo</label><input id="subtitulo" class="form-control"></div>
<div class="col-md-3"><label class="form-label">Abertura</label><input id="abertura" type="datetime-local" class="form-control"></div><div class="col-md-3"><label class="form-label">Fechamento</label><input id="fechamento" type="datetime-local" class="form-control"></div><div class="col-md-6"><label class="form-label">Mensagem antes de abrir</label><input id="mensagem_antes" class="form-control"></div>
<div class="col-md-6"><label class="form-label">Mensagem quando fechado</label><input id="mensagem_fechado" class="form-control"></div><div class="col-md-6"><label class="form-label">Mensagem após inscrição</label><input id="mensagem_sucesso" class="form-control" value="Inscrição realizada com sucesso."></div><div class="col-md-3"><label class="form-label">Posição do editor</label><select id="editor_posicao" class="form-select"><option value="esquerda">Esquerda</option><option value="direita">Direita</option><option value="acima">Acima</option><option value="abaixo">Abaixo</option></select></div><div class="col-md-9"><label class="form-label">Conteúdo do editor</label><textarea id="editor_conteudo" class="form-control" rows="2"></textarea></div>
</div></div></div>
<div class="card content-card mb-4"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h5 fw-bold mb-0">Estrutura</h2><div class="d-flex gap-2"><button type="button" class="btn btn-outline-secondary btn-sm" id="addGroup"><i class="bi bi-collection me-1"></i>Grupo</button><button type="button" class="btn btn-outline-secondary btn-sm" id="addFieldset"><i class="bi bi-bounding-box me-1"></i>Fieldset</button><button type="button" class="btn btn-primary btn-sm" id="addRow"><i class="bi bi-layout-three-columns me-1"></i>Linha</button></div></div><div class="card-body" id="builderRows"></div></div>
<div class="d-flex gap-2"><button class="btn btn-primary"><i class="bi bi-save me-1"></i>Salvar formulário</button><button type="button" class="btn btn-outline-info" id="testForm"><i class="bi bi-play-circle me-1"></i>Testar formulário</button><a href="{{ route('atividades.inscricoes',$atividade) }}" class="btn btn-outline-warning"><i class="bi bi-person-lines-fill me-1"></i>Inscrições</a></div>
</form>
@endsection
@push('scripts')
<script>
const initial={{ Illuminate\Support\Js::from(json_decode(old('formulario', 'null'), true) ?? $atividade->formulario ?? []) }};let rows=initial.rows||[{columns:[{fields:initial.campos||[]}]}],groups=initial.grupos||[],fieldsets=initial.fieldsets||[],fieldId=0;
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
function fieldHtml(field={}){fieldId++;return `<div class="border rounded p-2 mb-2 field"><div class="row g-2"><div class="col-md-3"><input class="form-control form-control-sm f-label" placeholder="Label" value="${esc(field.label)}"></div><div class="col-md-3"><input class="form-control form-control-sm f-name" placeholder="Nome único" value="${esc(field.nome)}"></div><div class="col-md-2"><select class="form-select form-select-sm f-type"><option value="text">Texto</option><option value="date">Data</option><option value="datetime-local">Data/hora</option><option value="textarea">Textarea</option><option value="file">Upload</option><option value="select">Combo</option><option value="radio">Radio</option><option value="checkbox">Checkbox</option><option value="multiselect">Multiselect</option></select></div><div class="col-md-2"><input class="form-control form-control-sm f-placeholder" placeholder="Placeholder" value="${esc(field.placeholder)}"></div><div class="col-md-1 form-check pt-1"><input class="form-check-input f-required" type="checkbox" ${field.obrigatorio?'checked':''}><label class="form-check-label small">Obrig.</label></div><div class="col-md-1 text-end"><button type="button" class="btn btn-sm btn-outline-danger remove-field" title="Remover"><i class="bi bi-trash"></i></button></div><div class="col-12"><input class="form-control form-control-sm f-options" placeholder="Opções separadas por vírgula" value="${esc((field.opcoes||[]).join(', '))}"></div><div class="col-md-3"><input class="form-control form-control-sm f-accept" placeholder="Tipos aceitos: pdf,jpg" value="${esc((field.aceitos||[]).join(','))}"></div><div class="col-md-2"><input class="form-control form-control-sm f-max" type="number" min="1" max="10" placeholder="Máx. arquivos" value="${field.max_arquivos||1}"></div><div class="col-md-3"><select class="form-select form-select-sm f-validation"><option value="">Validação</option><option value="cpf">CPF</option><option value="telefone">Telefone</option><option value="email">E-mail</option></select></div></div></div>`}
function columnHtml(){return '<div class="col-md-6 builder-column"><div class="bg-light border rounded p-2"><div class="d-flex justify-content-between mb-2"><span class="small fw-semibold">Coluna</span><button type="button" class="btn btn-sm btn-outline-success add-field"><i class="bi bi-plus-lg"></i> Campo</button></div><div class="fields"></div></div></div>'}
function render(){const root=document.getElementById('builderRows');root.innerHTML='';rows.forEach((row,index)=>{const el=document.createElement('div');el.className='border rounded p-3 mb-3 builder-row';el.innerHTML=`<div class="d-flex justify-content-between mb-2"><strong>Linha ${index+1}</strong><button type="button" class="btn btn-sm btn-outline-primary add-column"><i class="bi bi-layout-sidebar-inset"></i> Coluna</button></div><div class="row g-3 columns"></div>`;const cols=el.querySelector('.columns');row.columns.forEach(col=>{const wrapper=document.createElement('div');wrapper.innerHTML=columnHtml();const c=wrapper.firstChild;col.fields.forEach(field=>{c.querySelector('.fields').insertAdjacentHTML('beforeend',fieldHtml(field));const el=c.querySelector('.fields').lastElementChild;el.querySelector('.f-type').value=field.tipo||'text';el.querySelector('.f-validation').value=field.validacao||''});cols.appendChild(c)});root.appendChild(el)})}
document.getElementById('builderRows').addEventListener('click',event=>{if(event.target.closest('.remove-field'))event.target.closest('.field').remove();if(event.target.closest('.add-field'))event.target.closest('.builder-column').querySelector('.fields').insertAdjacentHTML('beforeend',fieldHtml());if(event.target.closest('.add-column'))event.target.closest('.builder-row').querySelector('.columns').insertAdjacentHTML('beforeend',columnHtml())});
document.getElementById('addRow').onclick=()=>{rows=build().rows;rows.push({columns:[{fields:[]}]});render()};document.getElementById('addGroup').onclick=()=>{const name=prompt('Nome do grupo');if(name)groups.push(name)};document.getElementById('addFieldset').onclick=()=>{const name=prompt('Título do fieldset');if(name)fieldsets.push(name)};
function build(){const campos=[...document.querySelectorAll('.field')].map((el,index)=>({label:el.querySelector('.f-label').value,nome:el.querySelector('.f-name').value||`campo_${index+1}`,tipo:el.querySelector('.f-type').value,placeholder:el.querySelector('.f-placeholder').value,obrigatorio:el.querySelector('.f-required').checked,opcoes:el.querySelector('.f-options').value.split(',').map(v=>v.trim()).filter(Boolean),aceitos:el.querySelector('.f-accept').value.split(',').map(v=>v.trim()).filter(Boolean),max_arquivos:Math.min(10,Math.max(1,Number(el.querySelector('.f-max').value)||1)),validacao:el.querySelector('.f-validation').value}));let offset=0;const grid=[...document.querySelectorAll('.builder-row')].map(row=>({columns:[...row.querySelectorAll(':scope > .columns > .builder-column')].map(col=>{const count=col.querySelectorAll('.field').length;const fields=campos.slice(offset,offset+count);offset+=count;return {fields}})}));return {titulo:document.getElementById('titulo').value,subtitulo:document.getElementById('subtitulo').value,abertura:document.getElementById('abertura').value,fechamento:document.getElementById('fechamento').value,mensagem_antes:document.getElementById('mensagem_antes').value,mensagem_fechado:document.getElementById('mensagem_fechado').value,mensagem_sucesso:document.getElementById('mensagem_sucesso').value,editor:{posicao:document.getElementById('editor_posicao').value,conteudo:document.getElementById('editor_conteudo').value},grupos:groups,fieldsets,campos,rows:grid}}
document.getElementById('formBuilder').addEventListener('submit',event=>{try{document.getElementById('formularioJson').value=JSON.stringify(build())}catch(error){event.preventDefault();console.error(error);alert('Não foi possível preparar o formulário para salvar. Tente novamente.')}});document.getElementById('testForm').onclick=async()=>{const response=await fetch(@json(route('atividades.formulario.preview-link',$atividade)));const data=await response.json();window.open(data.url,'_blank')};
const mensagensPadrao={mensagem_antes:'As inscrições ainda não estão abertas. Confira a data de abertura e volte em breve para participar!',mensagem_fechado:'As inscrições para esta atividade estão encerradas. Agradecemos seu interesse e esperamos você nas próximas oportunidades!',mensagem_sucesso:'Inscrição realizada com sucesso! Recebemos suas respostas. Agradecemos sua participação!'};
['titulo','subtitulo','abertura','fechamento','mensagem_antes','mensagem_fechado','mensagem_sucesso'].forEach(id=>document.getElementById(id).value=(mensagensPadrao[id]&&!String(initial[id]??'').trim()?mensagensPadrao[id]:initial[id]??''));document.getElementById('editor_conteudo').value=initial.editor?.conteudo||'';document.getElementById('editor_posicao').value=initial.editor?.posicao||'esquerda';render();
</script>
@endpush
