@extends('layouts.app')
@section('title','Participantes')
@push('styles')<link href="https://cdn.datatables.net/2.3.2/css/dataTables.bootstrap5.min.css" rel="stylesheet">@endpush
@section('content')
<div class="mb-4 d-flex justify-content-between gap-3"><div><h1 class="page-title">Participantes</h1><p class="page-description mb-0">Participantes cadastrados no sistema de certificados.</p></div>@if(app(\App\Services\GiPermissionService::class)->permite('participantes.criar'))<a href="{{route('participantes.create')}}" class="btn btn-primary align-self-start"><i class="bi bi-plus-lg me-1"></i>Novo participante</a>@endif</div>
@if(session('status'))<div class="alert alert-success">{{session('status')}}</div>@endif<div id="feedback" class="alert d-none"></div>
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">Participantes cadastrados</h2></div><div class="card-body p-0"><div class="table-responsive"><table id="participantesTable" class="table table-hover align-middle w-100 mb-0"><thead><tr><th>ID</th><th>Nome</th><th>E-mail</th><th>E-mail 2</th><th>E-mail institucional</th><th>Instituição de ensino</th><th>CPF</th><th>Status</th><th>Criado em</th><th>Atualizado em</th><th data-dt-order="disable">Ações</th></tr></thead></table></div></div></div>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.bootstrap5.min.js"></script><script>
document.addEventListener('DOMContentLoaded',()=>{const table=new DataTable('#participantesTable',{processing:true,serverSide:true,order:[[0,'desc']],pageLength:@json($estadoTabela['por_pagina']),displayStart:@json(($estadoTabela['page']-1)*$estadoTabela['por_pagina']),search:{search:@json($estadoTabela['pesquisar'])},ajax:@json(route('participantes.dados',[],false)),columns:[{data:'id'},{data:'nome'},{data:'email'},{data:'email2'},{data:'email_institucional'},{data:'instituicao_ensino'},{data:'cpf'},{data:'ativo'},{data:'criado_em'},{data:'atualizado_em'},{data:'acoes',orderable:false,searchable:false}],language:{processing:'Carregando...',emptyTable:'Nenhum participante cadastrado.',info:'Exibindo _START_ a _END_ de _TOTAL_ participantes',infoEmpty:'Nenhum participante encontrado',lengthMenu:'Exibir _MENU_ registros',search:'Pesquisar:',zeroRecords:'Nenhum participante encontrado.',paginate:{next:'Próxima',previous:'Anterior'}}});document.getElementById('participantesTable').onclick=async e=>{const b=e.target.closest('[data-delete-url]');if(!b||!confirm('Excluir este participante?'))return;b.disabled=true;try{const r=await fetch(b.dataset.deleteUrl,{method:'DELETE',credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':@json(csrf_token())}});const p=await r.json();if(!r.ok)throw new Error(p.message);table.ajax.reload(null,false)}catch(x){const f=document.getElementById('feedback');f.textContent=x.message||'Falha ao excluir.';f.classList.remove('d-none');f.classList.add('alert-danger');b.disabled=false}}});
</script>@endpush
