@php($c = $configuracaoPadrao)
<div class="card content-card mb-4">
    <div class="card-header"><h2 class="h5 fw-bold mb-0">Configuração da página padrão</h2></div>
    <div class="card-body p-4">
        <p class="text-muted">Esta configuração é usada quando o evento está sem template. A página pública é montada automaticamente com os cards selecionados.</p>
        <div class="row g-3 mb-4">
            <div class="col-md-4"><label class="form-label fw-semibold">Largura da página</label><select class="form-select" name="pagina_padrao[layout]"><option value="fixo" @selected(old('pagina_padrao.layout',$c['layout'])==='fixo')>Fixa (recomendada)</option><option value="fluido" @selected(old('pagina_padrao.layout',$c['layout'])==='fluido')>Fluida</option></select></div>
            <div class="col-md-4"><label class="form-label fw-semibold">Fundo do card</label><select class="form-select" name="pagina_padrao[card_tipo]"><option value="solida" @selected($c['card']['tipo']==='solida')>Cor sólida</option><option value="degrade" @selected($c['card']['tipo']==='degrade')>Degradê</option></select></div>
            <div class="col-md-4"><label class="form-label fw-semibold">Cor do card</label><div class="input-group"><input class="form-control form-control-color" type="color" value="{{ $c['card']['solida'] }}" data-cor-picker><input class="form-control font-monospace" type="text" name="pagina_padrao[card_solida]" value="{{ $c['card']['solida'] }}" maxlength="7" pattern="#[0-9a-fA-F]{6}" data-cor-text></div></div>
        </div>
        <div class="border rounded-3 p-3 mb-4">
            <h3 class="h6 fw-bold">Cabeçalho</h3><div class="row g-3">
                <div class="col-md-3"><label class="form-label">Fundo</label><select class="form-select" name="pagina_padrao[cabecalho_tipo]"><option value="degrade" @selected($c['cabecalho']['tipo']==='degrade')>Degradê</option><option value="solida" @selected($c['cabecalho']['tipo']==='solida')>Cor sólida</option><option value="imagem" @selected($c['cabecalho']['tipo']==='imagem')>Imagem</option></select></div>
                @foreach(['cabecalho_inicio'=>['Início do degradê','inicio'],'cabecalho_fim'=>['Fim do degradê','fim'],'cabecalho_solida'=>['Cor sólida','solida'],'cabecalho_fonte'=>['Cor do texto','fonte']] as $campo=>$item)<div class="col-md-2"><label class="form-label">{{ $item[0] }}</label><div class="input-group"><input class="form-control form-control-color" type="color" value="{{ $c['cabecalho'][$item[1]] }}" data-cor-picker><input class="form-control font-monospace" type="text" name="pagina_padrao[{{ $campo }}]" value="{{ $c['cabecalho'][$item[1]] }}" maxlength="7" pattern="#[0-9a-fA-F]{6}" data-cor-text></div></div>@endforeach
                <div class="col-md-3"><label class="form-label">Imagem do cabeçalho</label><input class="form-control" type="file" name="imagem_pagina_cabecalho" accept="image/jpeg,image/png,image/webp"></div>
            </div>
        </div>
        <div class="border rounded-3 p-3 mb-4"><div class="row g-3 align-items-end"><div class="col-md-3"><div class="form-check"><input class="form-check-input" type="checkbox" name="pagina_padrao[mostrar_imagem_evento]" value="1" @checked($c['mostrar_imagem_evento'])><label class="form-check-label fw-semibold">Mostrar imagem do evento</label></div></div><div class="col-md-3"><label class="form-label">Altura do card (px)</label><input class="form-control" type="number" name="pagina_padrao[altura_imagem_evento]" min="100" max="700" value="{{ $c['altura_imagem_evento'] }}"></div><div class="col-md-6"><label class="form-label">Imagem do evento</label><input class="form-control" type="file" name="imagem_pagina_evento" accept="image/jpeg,image/png,image/webp"></div></div></div>
        <div class="border rounded-3 p-3 mb-4"><h3 class="h6 fw-bold">Informações do evento</h3><input type="hidden" id="paginaConteudoHtml" name="pagina_padrao[conteudo_html]" value="{{ old('pagina_padrao.conteudo_html',$c['conteudo']['html']) }}"><div id="paginaConteudoEditor" class="border rounded" style="min-height:220px"></div><div class="row g-3 mt-1"><div class="col-md-4"><label class="form-label">Altura do conteúdo</label><select class="form-select" name="pagina_padrao[conteudo_altura]"><option value="auto" @selected($c['conteudo']['altura']==='auto')>Automática</option><option value="fixa" @selected($c['conteudo']['altura']==='fixa')>Definida</option></select></div><div class="col-md-4"><label class="form-label">Altura definida (px)</label><input class="form-control" type="number" name="pagina_padrao[conteudo_altura_px]" min="160" max="3000" value="{{ $c['conteudo']['altura_px'] }}"></div></div></div>
        @if($submissoes->isNotEmpty())
        <div class="border rounded-3 p-3 mb-4"><h3 class="h6 fw-bold">Cards de submissão</h3><p class="text-muted small">Existe um card para cada cadastro de submissão associado a este evento. Os textos podem ser formatados pelo editor.</p>
            @foreach($submissoes as $submissao)
                @php($sc = collect($c['submissoes'] ?? [])->firstWhere('submissao_id', $submissao->id) ?: \App\Models\PaginaPadraoEvento::submissaoPadrao($submissao->id, $submissao->titulo))
                <div class="border rounded-3 p-3 mb-3 submissao-config" data-submissao-config>
                    <h4 class="h6 mb-3">{{ $submissao->titulo }} <span class="text-muted fw-normal">(#{{ $submissao->id }})</span></h4>
                    <input type="hidden" name="pagina_padrao[submissoes][{{ $submissao->id }}][submissao_id]" value="{{ $submissao->id }}">
                    <div class="row g-3">
                        <div class="col-12 col-lg-6"><label class="form-label">Título da coluna esquerda</label><input type="hidden" name="pagina_padrao[submissoes][{{ $submissao->id }}][titulo_html]" value="{{ $sc['titulo_html'] }}" data-editor-hidden><div class="border rounded submissao-editor" data-editor-value="{{ $sc['titulo_html'] }}"></div></div>
                        <div class="col-12 col-lg-6"><label class="form-label">Texto da coluna direita</label><input type="hidden" name="pagina_padrao[submissoes][{{ $submissao->id }}][descricao_html]" value="{{ $sc['descricao_html'] }}" data-editor-hidden><div class="border rounded submissao-editor" data-editor-value="{{ $sc['descricao_html'] }}"></div></div>
                        <div class="col-md-3"><label class="form-label">Fundo</label><select class="form-select" name="pagina_padrao[submissoes][{{ $submissao->id }}][fundo_tipo]"><option value="solida" @selected($sc['fundo_tipo']==='solida')>Cor sólida</option><option value="degrade" @selected($sc['fundo_tipo']==='degrade')>Degradê</option></select></div>
                        @foreach(['fundo_solida'=>'Cor sólida','fundo_inicio'=>'Início do degradê','fundo_fim'=>'Fim do degradê','fonte'=>'Cor da fonte','botao_fundo'=>'Cor do botão','botao_fonte'=>'Cor do texto do botão'] as $campo=>$rotulo)
                            <div class="col-md-3"><label class="form-label">{{ $rotulo }}</label><div class="input-group"><input class="form-control form-control-color" type="color" value="{{ $sc[$campo] }}" data-cor-picker><input class="form-control font-monospace" type="text" name="pagina_padrao[submissoes][{{ $submissao->id }}][{{ $campo }}]" value="{{ $sc[$campo] }}" maxlength="7" pattern="#[0-9a-fA-F]{6}" data-cor-text></div></div>
                        @endforeach
                        <div class="col-md-6"><label class="form-label">Texto do botão</label><input class="form-control" name="pagina_padrao[submissoes][{{ $submissao->id }}][botao_texto]" maxlength="100" value="{{ $sc['botao_texto'] }}"></div>
                    </div>
                </div>
            @endforeach
        </div>
        @endif
        <div class="border rounded-3 p-3 mb-4"><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="pagina_padrao[cronograma_mostrar]" value="1" @checked($c['cronograma']['mostrar'])><label class="form-check-label fw-semibold">Mostrar cronograma</label></div><div id="cronogramaLinhas" class="vstack gap-2"></div><button type="button" class="btn btn-sm btn-outline-primary mt-3" id="adicionarEtapa">Adicionar etapa</button><input type="hidden" name="pagina_padrao[cronograma_json]" id="cronogramaJson" value='@json($c['cronograma']['etapas'])'></div>
        <div class="border rounded-3 p-3 mb-4"><h3 class="h6 fw-bold">Participantes / convidados</h3><div class="row g-3"><div class="col-md-3"><div class="form-check"><input class="form-check-input" type="checkbox" name="pagina_padrao[participantes_mostrar]" value="1" @checked($c['participantes']['mostrar'])><label class="form-check-label">Mostrar card</label></div></div><div class="col-md-3"><div class="form-check"><input class="form-check-input" type="checkbox" name="pagina_padrao[participantes_foto]" value="1" @checked($c['participantes']['foto'])><label class="form-check-label">Mostrar foto</label></div></div><div class="col-md-3"><div class="form-check"><input class="form-check-input" type="checkbox" name="pagina_padrao[participantes_redes]" value="1" @checked($c['participantes']['redes'])><label class="form-check-label">Mostrar redes sociais</label></div></div><div class="col-md-3"><div class="form-check"><input class="form-check-input" type="checkbox" name="pagina_padrao[participantes_curriculo]" value="1" @checked($c['participantes']['curriculo'])><label class="form-check-label">Mostrar currículo</label></div></div><div class="col-md-3"><label class="form-label">Cards por linha</label><select class="form-select" name="pagina_padrao[participantes_colunas]"><option value="2" @selected($c['participantes']['colunas']===2)>2</option><option value="3" @selected($c['participantes']['colunas']===3)>3</option><option value="4" @selected($c['participantes']['colunas']===4)>4</option></select></div></div></div>
        <div class="border rounded-3 p-3 mb-4"><h3 class="h6 fw-bold">Atividades</h3><div class="row g-3"><div class="col-md-4"><div class="form-check"><input class="form-check-input" type="checkbox" name="pagina_padrao[atividades_mostrar]" value="1" @checked($c['atividades']['mostrar'])><label class="form-check-label">Mostrar atividades</label></div></div><div class="col-md-4"><div class="form-check"><input class="form-check-input" type="checkbox" name="pagina_padrao[atividades_agrupar]" value="1" @checked($c['atividades']['agrupar_categoria'])><label class="form-check-label">Agrupar por categoria</label></div></div><div class="col-md-4"><div class="form-check"><input class="form-check-input" type="checkbox" name="pagina_padrao[atividades_inscricao]" value="1" @checked($c['atividades']['mostrar_inscricao'])><label class="form-check-label">Mostrar botão de inscrição</label></div></div></div></div>
        <div class="border rounded-3 p-3 mb-4"><h3 class="h6 fw-bold">Cards adicionais</h3><div id="cardsLinhas" class="vstack gap-2"></div><button type="button" class="btn btn-sm btn-outline-primary mt-3" id="adicionarCard">Adicionar card</button><input type="hidden" name="pagina_padrao[cards_json]" id="cardsJson" value='@json($c['cards'])'></div>
        <div class="border rounded-3 p-3"><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="pagina_padrao[faq_mostrar]" value="1" @checked($c['faq']['mostrar'])><label class="form-check-label fw-semibold">Mostrar perguntas frequentes</label></div><div id="faqLinhas" class="vstack gap-2"></div><button type="button" class="btn btn-sm btn-outline-primary mt-3" id="adicionarFaq">Adicionar pergunta</button><input type="hidden" name="pagina_padrao[faq_json]" id="faqJson" value='@json($c['faq']['itens'])'></div>
    </div>
</div>
@push('styles')<link href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" rel="stylesheet">@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-cor-picker]').forEach(picker=>{const text=picker.parentElement.querySelector('[data-cor-text]');picker.addEventListener('input',()=>text.value=picker.value);text.addEventListener('input',()=>{if(/^#[0-9a-fA-F]{6}$/.test(text.value))picker.value=text.value})})});</script>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const toolbar=[['bold','italic','underline'],[{header:[1,2,3,false]}],[{list:'ordered'},{list:'bullet'}],['link','clean']];const editores=[];document.querySelectorAll('[data-editor-hidden]').forEach(hidden=>{const alvo=hidden.parentElement.querySelector('.submissao-editor');const editor=new Quill(alvo,{theme:'snow',modules:{toolbar}});editor.clipboard.dangerouslyPasteHTML(hidden.value||'');editores.push([editor,hidden])});const form=document.querySelector('form');form.addEventListener('submit',()=>editores.forEach(([editor,hidden])=>hidden.value=editor.root.innerHTML))});</script>@endpush
